### ISSUE TITLE
ctx cl must be overridden to plugin cl

### ISSUE THREAD

**Issue by Splatcrafter** [temez/springlify#32]
Hello, i'm testing the project since a few hours and found that the ClassLoader could not find DB Drivers like org.mariadb.jdbc.Driver or a h2 db.

The issue i'm always getting is the following:

```
[14:47:39 WARN]: java.lang.ClassNotFoundException: org.mariadb.jdbc.Driver
[14:47:39 WARN]:        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[14:47:39 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[14:47:39 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[14:47:39 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[14:47:39 WARN]:        at java.base/java.lang.Class.forName(Class.java:534)
[14:47:39 WARN]:        at java.base/java.lang.Class.forName(Class.java:513)
[14:47:39 WARN]:        at springlify-test-1.0.0.jar//org.springframework.util.ClassUtils.forName(ClassUtils.java:304)
[14:47:39 WARN]:        at springlify-test-1.0.0.jar//org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.driverClassIsLoadable(DataSourceProperties.java:194)
[14:47:39 WARN]:        at springlify-test-1.0.0.jar//org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.determineDriverClassName(DataSourceProperties.java:175)
[14:47:39 WARN]:        at springlify-test-1.0.0.jar//org.springframework.boot.autoconfigure.jdbc.PropertiesJdbcConnectionDetails.getDriverClassName(PropertiesJdbcConnectionDetails.java:49)
[14:47:39 WARN]:        at springlify-test-1.0.0.jar//org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration.createDataSource(DataSourceConfiguration.java:55)
[14:47:39 WARN]:        at springlify-test-1.0.0.jar//org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari.dataSource(DataSourceConfiguration.java:117)
[14:47:39 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
```

There is also many other stuff on the stacktrace after it, but this is the most part only Spring internal stuff.
It seems that the ClassLoader could not get recocnized correctly. Mabye i'm wrong but for me it seems that this is the problem because like we all know: Spigot and Paper uses different ClassLoaders for any plugin.

Could be useful to review this issue because programming via. jpa is not possible because of this.

Here is some additional information from my application.yml and the pom.

pom.xml dependencies:
```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
            <version>3.3.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
            <version>3.3.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>3.3.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
            <version>3.3.0</version>
            <scope>compile</scope>
        </dependency>
```

application.yml:

```yaml
spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/testspring"
    username: "spring"
    password: "password"
    driver-class-name: "org.mariadb.jdbc.Driver" # <- Driver for adressing the issue
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
  profiles:
    active: dev
server:
  address: "127.0.0.1"
  port: 8081
  compression:
    enabled: true
  http2:
    enabled: true
```

Thanks for reading this and hopefully fixing this issue.
For additional informations i'm always contactable.

Kind Regards,
Erik Pförtner

**Comment by temez** [comment]
Hello. Can you please share your test project with me, I'll try to look at your problem today.

**Comment by Splatcrafter** [comment]
Yes of course. I'm sharing it in a few minutes.

**Comment by Splatcrafter** [comment]
https://github.com/Splatcrafter/Springlify-Test-Plugin/

This is the Plugin that i have written as a test for JPA. The DB Password and User is only a placeholder that is present at my localhost (my work pc).

I've forked the project on my pc to look at the code to fix it myself but couldn't figure it out until yet.
This code is refectored to your project but it seems that the libraries or the repo is not up-to-date. (With my forked version everything worked)

In my forked version i have not changed anything or only the way that it doesn't add the -plain.jar at the end. (This is because of Spring adds it by default)

**Comment by temez** [comment]
I'll look through your project, maybe you misconfigured something, because we tested data-jpa connectivity with PostgreSQL driver, everything worked.

**Comment by Splatcrafter** [comment]
I can try to use PostgreSQL instead of MariaDB for testing if this works.

**Comment by temez** [comment]
Try with PG, and try to remove `driver-class-name` from your `application.yml`, it's optional. Spring can discover your database platform from `url`.

**Comment by temez** [comment]
Also add `dev.temez.springlify` package to `scanBasePackages` in your `TestApplication`.

**Comment by Splatcrafter** [comment]
With the changes you said it recognizes the PostgreSQL, now it needs to work also with MariaDB and if it works i think this is done. But i need to also make it work with MariaDB.

**Comment by Splatcrafter** [comment]
It also works now with MariaDB but it says on start now that it could not satisfy my application because of the following trace:

```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'dev.temez.springlify.platform.text.converter.TextConverter' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

Idk if it is because of my changes in the Paper version i've made to make it work with mc 1.20.4 but this is an issue that i need to invastigate if it is no problem of configuration or something like this. What do you think, is is an config issue or code issue in the backend?

**Comment by temez** [comment]
Specify `springlify.platform.text-converter-mode` property with `legacy` or `mini_message`

**Comment by Splatcrafter** [comment]
Got it, thanks for the help, now i only need to clear my test database to show if the dao also works in general. If this works i'm sending the message here.

**Comment by temez** [comment]
I remembered, had similar issue with database connection, since then I never specified `driver-class-name` manually and forgot about it.

**Comment by Splatcrafter** [comment]
It now seems to have an visiblility error for the dao (DataAccessObject)/repository with this stacktrace:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userDao' defined in de.splatgames.springlify.testplugin.domain.dao.UserDao defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: org.springframework.data.jpa.repository.support.CrudMethodMetadata referenced from a method is not visible from class loader: java.net.URLClassLoader @4e515669
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788) ~[springlify-test-1.0.0.jar:?]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[springlify-test-1.0.0.jar:?]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[springlify-test-1.0.0.jar:?]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[springlify-test-1.0.0.jar:?]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[springlify-test-1.0.0.jar:?]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[springlify-test-1.0.0.jar:?]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[springlify-test-1.0.0.jar:?]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:969) ~[springlify-test-1.0.0.jar:?]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962) ~[springlify-test-1.0.0.jar:?]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[springlify-test-1.0.0.jar:?]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[springlify-test-1.0.0.jar:?]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[springlify-test-1.0.0.jar:?]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[springlify-test-1.0.0.jar:?]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:149) ~[springlify-test-1.0.0.jar:?]
        at dev.temez.springlify.initializer.SpringlifyInitializerImpl.initialize(SpringlifyInitializerImpl.java:66) ~[springlify-test-1.0.0.jar:?]
        at dev.temez.springlify.plugin.SpringlifyPlugin.initialize(SpringlifyPlugin.java:29) ~[springlify-test-1.0.0.jar:?]
        at dev.temez.springlify.plugin.SpringlifyBukkitPlugin.onEnable(SpringlifyBukkitPlugin.java:53) ~[springlify-test-1.0.0.jar:?]
        at de.splatgames.springlify.testplugin.TestPlugin.onEnable(TestPlugin.java:15) ~[springlify-test-1.0.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by temez** [comment]
Did you specify entities and repositories location via `@EnableJpaRepositories` or `@EntityScan`?

**Comment by Splatcrafter** [comment]
If this is that in my AppConfig i created a few minutes ago, than yes.

package de.splatgames.springlify.testplugin.configuration;

import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@Configuration
@EnableJpaRepositories(basePackages = "de.splatgames.springlify.testplugin.domain.dao")
@EntityScan(basePackages = "de.splatgames.springlify.testplugin.domain.entity")
public class AppConfig {
}

**Comment by temez** [comment]
Hmm, can you push changes to your repo?

**Comment by Splatcrafter** [comment]
Yes

**Comment by Splatcrafter** [comment]
Push is out

**Comment by temez** [comment]
I'll take a closer look in a couple of hours. Seems I'm missing the obvious

**Comment by Splatcrafter** [comment]
Okay, thanks. I'm also looking at it but i have no hope that i can fix it alone. Hopefully you can help later on.

**Comment by temez** [comment]
Sent you an invite to the example repo. Take a look at that project, maybe you will find something useful. If I figure out what happening, I'll write here.

**Comment by Splatcrafter** [comment]
I haven't discovered the solution yet. It seems that the issue is because of (like almost any issue that could be possible) a wrong ClassLoader is called but idk if this is true.

**Comment by Splatcrafter** [comment]
I've researched a bit and debugged the code. It seems that the ClassLoader in Spring tries to load the Class `org.springframework.data.jpa.repository.support.CrudMethodMetadata` from the `parentClassLoader` and not from the `org.bukkit.plugin.java.PluginClassLoader`. This is i think the main reason. But i have no clue how to fix this issue.

**Comment by Splatcrafter** [comment]
Update: Turns out, the `PluginClassLoader` of Paper (I hate this stupid modification) calls the super method on the `loadClass0(@NotNull String name, boolean resolve, boolean checkGlobal, boolean checkLibraries)` that calls the `super.loadClass(name, resolve);` which is the `URLClassLoader`. I don't see a workaround at the moment for it. Mabye you could get around this.

**Comment by Splatcrafter** [comment]
Thank you so much. I'm a bit out of power because of this issue right now.

**Comment by Splatcrafter** [comment]
I fixed it. It is only ONE f*cking line of Code!

```java
Thread.currentThread().setContextClassLoader(plugin.getPluginClassLoader());
```

(btw. i've modified the src a bit to make it work.)

**Comment by Splatcrafter** [comment]
Can i write an PullRequest for it to fix this?

**Comment by Kepchyk1101** [comment]
At this moment, please switch to postgres, mysql or h2 (tested) to avoid wasting your time. We will try to fix this in the future.

You can leave a pull request

**Comment by pq-artem-i** [comment]
> I fixed it. It is only ONE f*cking line of Code!
> 
> ```java
> Thread.currentThread().setContextClassLoader(plugin.getPluginClassLoader());
> ```
> 
> (btw. i've modified the src a bit to make it work.)

Hmmm, Bukkit moment. Leave a PR please, I'll push changes to the repo

**Comment by temez** [comment]
> I fixed it. It is only ONE f*cking line of Code!
> 
> ```java
> Thread.currentThread().setContextClassLoader(plugin.getPluginClassLoader());
> ```
> 
> (btw. i've modified the src a bit to make it work.)

Hmm, Bukkit moment. You can leave a PR, I'll push changes to the repo today.

**Comment by Splatcrafter** [comment]
This btw. calls the JavaPlugin.getClassLoader() method.

**Comment by temez** [comment]
> I leave a pr shortly after this message. Is it okay to add a method called `ClassLoader getPluginClassLoader();` to the class `dev.temez.springlify.plugin.SpringlifyPlugin` interface and implementing this in the `SpringlifyBukkitPlugin` by calling this to initialize it:
> 
> ```java
>   @Override
>   public ClassLoader getPluginClassLoader() {
>     return getClassLoader();
>   }
> ```

Yep, remove old `ClassLoader` implementation from `springlify-starter-common`

**Comment by Splatcrafter** [comment]
Should i fork the main branch or the dev? To create a new branch from one of these.

**Comment by pq-artem-i** [comment]
Create from dev

**Comment by temez** [comment]
Create from dev

**Comment by temez** [comment]
Thank you for PR, I'll review it shortly. If you have any new feature ideas or suggestions, you can always write an issue.

**Comment by temez** [comment]
@Splatcrafter pushed your changes to repo
